### ISSUE TITLE
protractor-conf.js does not exist

### ISSUE THREAD

**Issue by raam86** [tnajdek/angular-requirejs-seed#28]
module.js:340
    throw err;
          ^
Error: Cannot find module '/Users/raamroshhai/PhpstormProjects/DevPortal/config/protractor-conf.js'

**Comment by tnajdek** [comment]
Hey, we didn't have support for Protractor, instead opting for Karma to run our e2e tests. This has now changed and you should be able to use Protractor for running e2e tests.
