### ISSUE TITLE
service

### ISSUE THREAD

**Issue by yf0311** [tnajdek/angular-requirejs-seed#36]
![image](https://cloud.githubusercontent.com/assets/7891078/5918548/dd9c3604-a664-11e4-9661-6f507ca3e177.png)
![image](https://cloud.githubusercontent.com/assets/7891078/5918552/e679a018-a664-11e4-93b0-e542c56c0288.png)
![image](https://cloud.githubusercontent.com/assets/7891078/5918554/efc6e090-a664-11e4-98ac-effe133722e6.png)
![image](https://cloud.githubusercontent.com/assets/7891078/5918564/f9da29ac-a664-11e4-8c0c-b56e100b0e3c.png)
![image](https://cloud.githubusercontent.com/assets/7891078/5918569/0c608e68-a665-11e4-900f-5d306ac24d9a.png)
Why this error? How to solve

**Comment by tnajdek** [comment]
Apologies but this seems to be beyond the scope of the seed project. Also very hard to debug based on few screenshots.
