### ISSUE TITLE
Add jasmine to .jshintrc

### ISSUE THREAD

**Issue by acao** [tnajdek/angular-requirejs-seed#37]
if you add `jasmine: true` to .jshintrc, you won't have to do this at the top of all the specs:

`/*global describe, it, expect, beforeEach, afterEach, module, inject */ `

probably just this

`/*global module, inject */ `

also note the lack of the first space is important with defining globals. just offering this tip based on a cursory view.

**Comment by tnajdek** [comment]
good point!
